from .paciente import paciente
from .usuario import usuario
from .medico import medico
from .enfermero import enfermero
from .familiar import familiar
from .diagnostico import diagnostico
from .familiar import familiar
from .signosvitales import signosvitales
from .historiaclinica import historiaclinica
