# Generated by Django 4.1.1 on 2022-09-11 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diagnostico',
            fields=[
                ('id_diagnostico', models.IntegerField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=500)),
                ('sugernecia', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='enfermero',
            fields=[
                ('id_enfermero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombresapellidos', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('emali', models.CharField(max_length=50)),
                ('numeropacientes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='familiar',
            fields=[
                ('id_familiar', models.IntegerField(primary_key=True, serialize=False)),
                ('nombresapellidos', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('emali', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id_medico', models.IntegerField(primary_key=True, serialize=False)),
                ('nombresapellidos', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('emali', models.CharField(max_length=50)),
                ('numeropacientes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id_paciente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombresapellidos', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('emali', models.CharField(max_length=50)),
                ('enfermero_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.enfermero')),
                ('familiar_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.familiar')),
                ('medico_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.medico')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('contraseniausuarios', models.CharField(max_length=15)),
                ('tipousuario', models.CharField(max_length=15)),
                ('cedula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='signosvitales',
            fields=[
                ('id_signosvitales', models.IntegerField(primary_key=True, serialize=False)),
                ('signosvitales', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('enfermero_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.enfermero')),
                ('familiar_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.familiar')),
                ('medico_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.medico')),
                ('paciente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.usuario'),
        ),
        migrations.AddField(
            model_name='medico',
            name='usuario_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.usuario'),
        ),
        migrations.CreateModel(
            name='historiaclinica',
            fields=[
                ('id_historiaclinica', models.IntegerField(primary_key=True, serialize=False)),
                ('resumen', models.CharField(max_length=500)),
                ('diagnostico_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.diagnostico')),
                ('familiar_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.familiar')),
                ('medico_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.medico')),
                ('paciente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='familiar',
            name='usuario_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.usuario'),
        ),
        migrations.AddField(
            model_name='enfermero',
            name='usuario_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.usuario'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='enfermero_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.enfermero'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='familiar_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.familiar'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='medico_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.medico'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='paciente_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.paciente'),
        ),
    ]
